### ISSUE TITLE
Reg Installation Steps.

### ISSUE THREAD

**Issue by MayaV369** [sixthedge/opentbl#107]
Hi,

Can you share the installation step, system requirements and details for OpenTBL ?
Any VM Image , Docker or Vagrant image ?
waiting for your reply.

Thanks

**Comment by jamesfid** [comment]
Hi,

Unfortunately, this is no longer maintained as it is being absorbed into a larger project.

**Comment by MayaV369** [comment]
Hi,

So no more community edition?
