### ISSUE TITLE
[Roster] Updates for the roster.

### ISSUE THREAD

**Issue by jamesfid** [sixthedge/opentbl#14]
- [x] Table does not indicate sort direction when sorting.
- [x] `next_page` button does not seem to be functional (previous, go to last, etc are working).
- [x] Manual invitation process needs styling.
- [x] Upload of a roster is just at the bottom and not tied to the "Import Roster" button.
  - How should this work?

**Comment by jamesfid** [comment]
@jcamou Here's one thing that currently needs some style updates.

**Comment by jcamou** [comment]
Two buttons, upload roster and invite user, should work like the buttons here https://projects.invisionapp.com/d/main#/console/9758449/208758636/preview

**Comment by jcamou** [comment]
@jamesfid - are we adding a class when it's sorted or when the column is able to be sorted? I have a '.th__sortable' class that highlights the column

**Comment by jamesfid** [comment]
@jcamou Okay, I'll get the two buttons hooked up and add the class for sorting tomorrow.

**Comment by jamesfid** [comment]
@jcamou Got everything pushed up, just waiting on styling now at https://github.com/sixthedge/cellar/commit/ed3b2bf9f8cf481b7058e62c624d85a1a967e18a
