### ISSUE TITLE
[RAT] Missing radio button images

### ISSUE THREAD

**Issue by jamesfid** [sixthedge/opentbl#19]
Look into porting the radio buttons/options here to the accessibility version.
![image](https://cloud.githubusercontent.com/assets/215912/25784601/cd83aa80-3335-11e7-97ef-41e3a25f6ee8.png)

**Comment by jamesfid** [comment]
@jcamou Did the old radio image get removed?  Or, was it something I missed in the port?

**Comment by jcamou** [comment]
This might've been with the change to accessibility radio buttons. I'll look into it

**Comment by jamesfid** [comment]
Closed with https://github.com/sixthedge/cellar/commit/4fd6e2290f00762bee43e9b544b4a5e4999812a3
