### ISSUE TITLE
[Tables] Table issues

### ISSUE THREAD

**Issue by jcamou** [sixthedge/opentbl#23]
- [x] Column headers need role='columnheader'

- [x] Sorting through column headers should toggle so there's only one active sort 

- [x] Can we hide pagination buttons when they're not applicable?

- [x] List number of items rather than pages - This is more of a QoL

**Comment by jamesfid** [comment]
First three are addressed in: https://github.com/sixthedge/cellar/commit/ccee2a010a873dcc46e616e63c1885eb2199b736

**Comment by jamesfid** [comment]
Last is addressed in: https://github.com/sixthedge/cellar/commit/57d0325b46e235eec33b0175269cbaa562c25382

@jcamou Will need styling for the range text stuff.
