### ISSUE TITLE
[Builders] Remove the option to select a team set?  Or hide it under an "advanced" button or something?

### ISSUE THREAD

**Issue by jamesfid** [sixthedge/opentbl#28]
We could just remove the "Choose a team set" option in the builders.  We could keep the current one under an `advanced` flag, for now.

@sixthedge/dev  What do you think?  Since we're making it more "one team", this seems to make sense.

![image](https://cloud.githubusercontent.com/assets/215912/25935316/2f43ff04-35e8-11e7-93b3-a57c660ff74d.png)

**Comment by jcamou** [comment]
I vote for the advanced flag option and removing it from this page.

**Comment by devyngaspa** [comment]
Closed by https://github.com/sixthedge/cellar/commit/9bd4f3cf7a4b006973ce96eeb4d084689f67880c
