### ISSUE TITLE
[RAT Builder] Question IDs could collide.

### ISSUE THREAD

**Issue by jamesfid** [sixthedge/opentbl#29]
The way that the system is generating the `id` of a new question could have an issue.   It runs this function:
```
  get_next_id: (type) ->
    items = @get_items(type).sortBy('id')
    id    = items.get('lastObject.id')
    if ember.isPresent(id) then id = id + 1 else id = 1
```

Unlikely to happen, but this is possible:
  * You add 5 questions to the RAT.
  * Some students take a RAT.
  * Edit the RAT, remove the last question, add a new one.
    * Now the student answers for question 5 are incorrectly mapped.

@DylanBell Should we consider somethign like UUID or keeping track in the JSON of the last used or something?

**Comment by DylanBell** [comment]
@jamesfid currently the id is used for lookups, but nothing beyond that. I think we'd be well-served using a UUID. I found a few snippets for generating them on stackoverflow ([http://stackoverflow.com/questions/105034/create-guid-uuid-in-javascript](url)), and am gonna try tossing that code into a mixin.

**Comment by DylanBell** [comment]
There's also a couple of npm modules that do it..but given the outside chance of a collision use-case currently, I think the `Math.random()` approach should be sufficient.

**Comment by DylanBell** [comment]
Resolved by creating a `helpers/common/uuid.coffee` mixin, which contains a function to return a (reportedly) RFC4122 version 4 compliant UUID! (in commit [f5ffbc8](https://github.com/sixthedge/cellar/commit/f5ffbc8ea874b1a33e4fee4018311c35422637a8)
