### ISSUE TITLE
[RAT Builder] Answer dropdown does not get removed when you select an option.

### ISSUE THREAD

**Issue by jamesfid** [sixthedge/opentbl#30]
![image](https://cloud.githubusercontent.com/assets/215912/25935576/5bc9bac2-35e9-11e7-8a67-1de55cb15f00.png)
That's after selecting "A", it did not get removed from the DOM/hidden.

**Comment by DylanBell** [comment]
Talked with Devyn for a little bit about this one. Pretty sure it's a problem everywhere we're using the dropdown, and might take a bit of digging to resolve.
