### ISSUE TITLE
[RAT Builder] Setting a due date is causing 3 updates to fire

### ISSUE THREAD

**Issue by jamesfid** [sixthedge/opentbl#31]
The payloads look similar, so I don't think this is supposed to happen.  The net pane is from one click of a date:

![image](https://cloud.githubusercontent.com/assets/215912/25935649/c7f2bfa0-35e9-11e7-869d-776f4eff8eca.png)

**Comment by DylanBell** [comment]
Resolved in commit [f5ffbc8](https://github.com/sixthedge/cellar/commit/f5ffbc8ea874b1a33e4fee4018311c35422637a8)
