### ISSUE TITLE
[Team Builder] Missing pieces

### ISSUE THREAD

**Issue by jcamou** [sixthedge/opentbl#4]
**Student List**

- [ ] “Add to existing team” button should show up when student is selected
- [ ] "Create new team with selected" button should also show up when student is selected  
- [ ] Add student search (I can do this one if its just adding a component line)

**Team List**

- [ ] Not sure what the save button is doing there. does this mean actions taken at the "edit team" level aren't being saved? 

**General**

- [ ] Can we pull the teams section out so its under the main secondary nav - i.e., how the roster section is instead of sending you to `people/teams/roster` send you to `teams/roster`

**Comment by DylanBell** [comment]
Can't modify the checklist, but everything other than adding student search (and the save button conundrum) should be in commit [3d2956a](https://github.com/sixthedge/cellar/commit/3d2956acbda292a2f58333f940cb3bd6baba1c6b)

**Comment by jamesfid** [comment]
@jcamou Are any of these still valid?
