### ISSUE TITLE
[Rat Builder] Answers are not being loaded

### ISSUE THREAD

**Issue by DylanBell** [sixthedge/opentbl#43]
Currently we're not serializing the readiness assurance assessments' `answers` property. In order to get `answers` in the builder context, we'll need to use actions found in `cellar/src/thinkspace/api/thinkspace-readiness-assurance/app/controllers/thinkspace/readiness_assurance/api/admin/irats_controller.rb`

**Comment by jamesfid** [comment]
Also, there is a `trats_controller.rb` that does it for the tRAT phases.

**Comment by DylanBell** [comment]
Closed via PR#33 merge
