### ISSUE TITLE
[RAT Builder] Assignment release_at, due_at are not being set correctly.

### ISSUE THREAD

**Issue by jamesfid** [sixthedge/opentbl#44]
On staging, the assignment I created did not have its release_at and due_at set.  Likely a bug introduced by the refactor of how to set logistics on an assignment.

**Comment by DylanBell** [comment]
This is causing students to be unable to view cases they're assigned to. Taking a look at it.

**Comment by DylanBell** [comment]
Closed in commit [5feaee0](https://github.com/sixthedge/cellar/commit/5feaee08bd129e6db1cece9ce113b829771c4545)
