### ISSUE TITLE
[RAT Builder] When deleting a question, it removes all text you have added previously.

### ISSUE THREAD

**Issue by jamesfid** [sixthedge/opentbl#52]
* Add a new question.
* Edit the new question.
* Modify Choice A.
* Delete Choice D.
* Note that the text in Choice A was reset to the default value.

**Comment by DylanBell** [comment]
Looks like this is because we're recreating the choice objects using a `.@each` binding. Looking into how we might be able to refactor this

**Comment by DylanBell** [comment]
Closed via PR#33 merge
