### ISSUE TITLE
[TRAT] Submitting different answers from two different students does not give the first student priority

### ISSUE THREAD

**Issue by JLLogte** [sixthedge/opentbl#67]
When multiple team members are taking a TRAT, the student will see the answers that they personally submitted when going back to check the submission, rather than seeing the answers of the first team member to submit

**Comment by jamesfid** [comment]
@JLLogte Can you elaborate on a reproduction scenario for this?  I didn't think this would be possible, since it's the same record they're updating.

**Comment by JLLogte** [comment]
I tried to replicate it but this time it appeared to take the second person's submission as priority, which is still wrong but it's at least the same record. I'll keep testing it.

**Comment by JLLogte** [comment]
On a third test, it worked properly and showed the first submission for both team members. I did wait a bit longer before hitting submit on the second submission this time, I am curious to see if that has anything to do with what went wrong before. Going to test this some more.

**Comment by JLLogte** [comment]
Yeah, I think it was because I was submitting them in such a close timeframe. I hit submit on the one I intended to be the first submitter and then immediately went and hit submit on my second submitter, and it ended up taking the results of the second submission I input rather than the first. I still haven't replicated the submission where they both had their personal results, though.

**Comment by JLLogte** [comment]
Since I was unable to replicate the original issue after numerous attempts and the submission order appears to be working properly if I wait a few seconds before pressing the second submit button, I'm going to close this for now.
