### ISSUE TITLE
[Team Builder] Color domain data needs to be updated

### ISSUE THREAD

**Issue by DylanBell** [sixthedge/opentbl#68]
Currently we're using some pretty garish colors with some pretty obnoxious names as the possible selections in the team-builder. I know eventually we're looking to integrate a color picker, but for the time being the colors we're using can be modified in the file `thinkspace/api/thinkspace-common/db/domain_data/colors.yml`

**Comment by jcamou** [comment]
@DylanBell - I started doing this but the colors I added to the colors.yml weren't showing up as options. Is there something I got to do to reset or something? Planning on adding only colors that  meet the AA Guidelines

**Comment by DylanBell** [comment]
@jcamou once you've made changes to the `colors.yml`, and its been deployed, we'll need to do a `totem:db:domain:load` to get them into the database.
