### ISSUE TITLE
[PE] Legacy code removal

### ISSUE THREAD

**Issue by DylanBell** [sixthedge/opentbl#8]
Legacy files from builder-pe development need to be removed.

Specifically
 - `thinkspace-builder-pe/components/content/assessment/qual/item/preview.coffee`
 - `thinkspace-builder-pe/components/content/assessment/qual/item/settings.coffee`
 - `thinkspace-builder-pe/templates/components/content/assessment/qual/item/preview.emblem`
 - `thinkspace-builder-pe/templates/components/content/assessment/qual/item/settings.emblem`

There may be other files as well, but those ones definitely need removal.

**Comment by devyngaspa** [comment]
Closed by https://github.com/sixthedge/cellar/commit/bf3ebe6ed8d1a9b1f8d93e1e7022aeaa22d8dd9a
